# Feito por Kauã e Afonso

define mv = Character("Madalena de Vilhena")
define tp = Character("Telmo Pais")
define mn = Character("D. Maria de Noronha")
define fj = Character("Frei Jorge")
define mc = Character("Manuel de Sousa Coutinho")
define jp = Character("D. João de Portugal")
define m = Character("Miranda (E outros criados)")
define t = Character("Todos juntos")

label ato1:
    "Câmera antiga, jornada com todo o luxo e caprichosa elegância portuguesa dos princípios do século dezassete"
    "Porcelanas, jarrões, sedas, flores, etc."
    "No fundo, duas grandes janelas rasgadas, dando para um eirado que olha sobre o Tejo e donde se vê toda Lisboa"
    "Entre as janelas o retrato, em corpo inteiro, de um cavaleiro moço, vestido de preto, com a cruz branca de noviço de S. João de Jerusalém"
    "Em frente e para a boca da cena um bufete pequeno, coberto de rico pano de veludo verde franjado de prata"
    "Sobre o bufete alguns livros, obras de tapeçaria meias feitas e um vaso da China de colo alto, com flores."
    "Algumas cadeiras antigas, tamboretes rasos, contadores. Da direita do espectador, porta de comunicação para o interior da casa, outra da esquerda para o exterior. É no fim da tarde."
    jump cena1

# Parte do Kauã (Pág. 64 a 78)
label cena1: 
    "Madalena sentada com os pés junto a mesa, abre um livro e se descai na leitura sobre meditação"
    "Madalena, repetindo maquinalmente e devagar o que acaba de ler:"
    mv "naquele engano d'alma ledo e cego"
    mv "Que a fortuna não deixa durar muito..."
    mv "com paz e alegria d'alma... um engano de poucos instantes"
    mv "que seja... deve ser a felicidade suprema neste mundo. E que importa que o"
    mv "não deixe durar muito  a fortuna? Viveu-se,pode-se morrer.Mas eu!...(pausa)"
    mv "Oh! que o não saiba ele ao menos,que não suspeite o estado em que"
    mv "eu vivo...este medo,estes continuos terrores, que ainda me não deixaram"
    mv "gozar um só momento de toda a imensa felicidade que me dava o seu amor."
    mv "Oh! que amor,que felicidade...que desgraça a minha!"
    "torna a descair em profunda meditação;silêncio breve:"

label cena2:
    "Telmo, chegando ao pé de Madalena, que o não sentiu entrar"
    "A minha senhora esta a ler?..."
    "Madalena, despertando"
    "Ah! sois vós, Telmo... Não, já não leio: há pouca luz de dia já; confundia-me a vista.E é um bonito livro, este! o teu valido, aquele nosso livro, Telmo"
    "Telmo, deitando-lhe os olhos - Oh! oh! livro para damas e para cavaleiros..."
    "E para todos: um livro que serve para todos, como não há outro, tirante o respeito devido ao da palavra de Deus! Mas esse não tenho eu a consolação de ler, que não sei latim como meu senhor..."
    "quero dizer como escolar é ele. E assim foi o seu pai antes dele, que muito bem o conheci: grande homem 10 Muitas letras, e de muito galante prática³, e não somenos as outras partes de cavaleiro: uma Sr. Manuel de Sousa Coutinho que, lá isso!..."
    "acabado gravidade!... Já não há daquela gente."
    "Mas, minha senhora, isto de a palavra de Deus estar assim noutra língua, numa língua que a gente..."
    "que toda a gente não entende..."
    "confer so-vos que aquele mercador inglês da Rua Nova, que aqui vem às vezes, tem-me dito sum cousas que me quadram..."
    "E Deus me perdoe, que eu creio que o homem é herege, det Alemanha ou de Inglaterra."
    "será?"
    "seita nova da Madalena Olhai, Telmo; eu não vos quero dar conselhos: bem sabeis que desde tempo que ..."
    "que..."
    "Telmo Que já lá vai, que era outro tempo."
    "Pois sim..."
    "madalena, suspira"
    "Eu era uma criança; pouco maior era que Maria."
    "Não, a senhora D. Maria já é mais alta."
    "É verdade, tem crescido de mais, e de repente, nestes de meses últimos..."~
    "Então! Tem treze anos feitos, é quase uma senhora, esti u 25 senhora..."
    "Telmo, a parte"
    "Uma senhora, aquela..."
    "pobre menina!"
    "Madalena, com as lágrimas nos olhos"
    "És muito amigo dela, Telmo?"
    "Se sou! Um anjo como aquele..."
    "uma viveza, um espírito...!"
    "e então que coração!"


# Parte do Afonso (Pág. 79 a 83)
label cena7: # Jorge, Madalena, Maria, Miranda, Manuel de Sousa entrando com vários criados que o seguem alguns com brandões acesos - É noite fechada
    "Manuel, parando junto da porta, para os criados, diz:"
    mc "Façam o que lhes disse, Já, sem mais detença!"
    mc "Não apaguem esses brandões, encostem-nos aí fora no patim."
    mc "E tudo o mais que eu mandei."
    "Manuel vai até ao proscénio, e fala com Madalena:"
    mc "Madalena! Minha querida filha, minha Maria!"
    "Manuel abraça-as e vira-se para Jorge"
    mc "Jorge, ainda bem que aqui estás, preciso de ti."
    mc "Bem sei que é tarde e que são horas conventuais, mas eu irei depois contigo a «mea culpa» e o «peccavi» ao nosso bom prior."
    mc "Miranda, vinde cá."
    "Manuel vai com ele à porta da esquerda, depois às do eirado, e dá-lhe algumas ordens baixo."
    mv "Que tens tu?"
    mv "Nunca entraste em casa assim."
    mv "Tens coisa que te dá cuidado... E não dizes? O que é?"
    mc "É que... Senta-te, Madalena. Aqui ao pé de mim, Maria."
    mc "Jorge, sentemo-nos que eu estou cansado."
    "Todos sentam-se junto a Manuel."
    mc "Pois agora sabei as novidades, que seriam estranhas se não fosse o tempo em que vivemos."
    "Manuel pausa, hesita antes de falar:"
    mc "É preciso sair já desta casa, Madalena."
    mn "Ah! Ainda bem, meu pai!"
    mc "Ainda mal! Mas não há outro remédio."
    mc "Sairemos esta noite mesma."
    mc "Já dei ordens a toda a família. Telmo foi avisar as tuas aias do que haviam de fazer, e lá andam pelas câmaras velando nesse cuidado."
    mc "Sempre é bom que vás dar um relance de olhos ao que por lá se faz, eu também irei por parte por minha parte."
    mc "Mas temos tempo, isto são oito horas, à meia-noite vão quatro, daqui lá o pouco que me importa salvar estará salvo..."
    mc "Eles não virão antes da manhã."
    mv "Então sempre é verdade que Luís de Moura e os outros governadores?..."
    mc "Luís de Moura é um vilão ruim, faz como quem é."
    mc "O arcebispo é... O que os outros querem que ele seja."
    mc "Mas o conde de Sabugal, o conde de Santa Cruz que deviam olhar por quem são, e que tomaram este encargo odioso..."
    mc "E vil, de oprimir os seus naturais em nome dum rei estrangeiro..."
    mc "Oh que gente, que fidalgos portugueses!"
    mc "Hei de lhes dar uma lição, a eles, e a este escravo deste povo que os sofre, como não levam tiranos há muito tempo nesta terra."
    mn "O meu nobre pai! Oh, meu querido pai!"
    mn "Sim, sim, mostrai-lhes quem sois e o que vale um português dos verdadeiros."
    mv "Meu adorado esposo, não te deites a perder, não te arrebates."
    mv "Que farás tu contra esses poderosos?"
    mv "Eles já te querem tão mal pelo mais que tu vales que eles, pelo teu saber."
    mv "Que essses grandes fingem que deprezam..."
    mv "Mas não é assim, o que eles têm é inveja!"
    mv "O que fará, se lhes deres pretexto para se vingarem da afronta em que os traz a superioridade do teu mérito!"
    mv "Manuel, meu esposo, Manuel de Sousa, pelo nosso amor..."
    jp "A tua mulher tem razão."
    jp "Prudência, e lembra-te de tua filha."
    mc "Lembro-me de tudo, deixa estar."
    mc "Não te inquietes, Madalena."
    mc "Eles querem vir para aqui amanhã de manhã, e nós forçosamente havemos de sair antes de eles entrarem."
    mc "Por isso é preciso já."
    mv "Mas para onde iremos nós, de repente, a estas horas?"
    mc "Para a única parte para onde podemos ir, a casa não é minha..."
    mc "Mas é tua, Madalena."
    mv "Qual?..."
    mv "A que foi..."
    mv "A que pega com S. Paulo?... Jesus me valha!"   
    jp "E fazem muito bem."
    jp "A casa é larga e está em bom reparo, tem ainda quase tudo de trastes e paramentos necessários." 
    jp "Pouco tereis que levar convosco."
    jp "E então para mim, para os nossos padres todos, que alegria!"
    jp "Ficamos quase debaixe dos mesmos telhados."
    jp "Sabeis que tendes ali tribuna para a capela da Senhora da Piedade, que é a mais devota e mais bela de toda a igreja..."
    jp "Ficamos como vivendo juntos."
    mn "Tomara-me eu já lá."
    "Maria levanta-se pulando"
    mc "E são horas, vamos a isto."
    "Manuel levanta-se"
    "Madalena, indo até Manuel:"
    mv "Ouve, escuta, que tenho que te dizer, por quem és, ouve... Não haverá algum outro modo?"
    mc "Qual, senhora, e que lhe hei de eu fazer? Lembrai vós, vede se achais."
    mv "Aquela casa... Eu não tenho ânimo..."
    mv "Olhai, eu preciso de falar a sós convosco."
    mv "Frei Jorge, ide com Maria para dentro, tenho que dizer a vosso irmão."
    mn "Tio, venha, quero ver se me acomodam os meus livrinhos."
    "Maria diz, confidencialmente:"
    mn "E os meus papéis, que eu também tenho papéis."
    mn "Deixai que lá na outra casa vos hei de mostrar..."
    mn "Mas segredo!"
    jp "Tontinha."
    jump cena8

label cena8: # Manuel de Sousa, Madalena
    "Manuel, passeia agitado de um lado para outro da cena, com as mãos cruzadas detrás das costas, e parando de repente:"
    mc "Há de saber-se no mundo que ainda há um português em Portugal."
    mv "Que tens tu, dize, que tens tu?"
    mc "Tenho que não hei de sofrer esta afronta..."
    mc "E que é preciso sair desta casa, senhora."
    mv "Pois sairemos, sim."
    mv "Eu nunca me opus ao teu querer, nunca soube que coisa era ter outra vontade diferente da tua, estou pronta a obedecer-te sempre, cegamente, em tudo."
    mv "Mas, oh!"
    mv "Esposo da minha alma..."
    mv "Para aquela casa não, não me leves para aquela casa."
    "Madalena deita-lhe os braços ao pescoço"
    mc "Ora tu não eras costumada a ter caprichos!"
    mc "Não temos outra para onde ir, e a estas horas, neste aperto."
    mc "Mudaremos depois, se quiseres..."
    mc "Mas não lhe vejo remédio agora."
    mc "E a casa que tem?"
    mc "Porque foi de teu primeiro marido!"
    mc "É por mim que tens essa repugnância?"
    mc "Eu estimei e respeitei sempre a D. João de Portugal."
    mc "Honro a sua memória, por ti, por ele e por mim."
    mc "E não tenho na consciência por que receie abrigar-me debaixo dos mesmos tetos que o cobriram."
    mc "Viveste ali com ele?"
    mc "Eu não tenho ciúmes de um passado que me não pertencia."
    mc "E o presente, esse é meu, meu só, todo meu, querida Madalena..."
    mc "Não falemos mais nisso, é preciso partir, e já."
    mv "Mas é que tu não sabes..."
    mv "Eu não sou melindrosa nem de invenções, em tudo o mais sou mulher, e muito mulher, querido."
    mv "Nisso não..."
    mv "Mas tu não sabes a violência, o constrangimento de alma, o terror com que eu penso em ter de entrar naquela casa."
    mv "Parece-me que é voltar ao poder dele, que é tirar-me dos teus braços, que o vou encontrar ali..."
    mv "Oh perdoa, perdoa-me, não me sai esta ideia da cabeça..."
    mv "Que vou achar ali a sombra despeitosa de D. João que me está ameaçando com uma espada de dois gumes..."
    mv "Que a atravessa no meio de nós, entre mim e ti e a nossa filha, que nos vai separar para sempre..."
    mv "Que queres?"
    mv "Bem sei que é loucura."
    mv "Mas a ideia de tornar a morar ali, de viver ali contigo e com Maria, não posso com ela."
    mv "Sei decerto que vou ser infeliz, que vou morrer naquela casa funesta, que não estou ali três dias, três horas, sem que todas as calamidades do mundo venham sobre nós."
    mv "Meu esposo, Manuel, marido da minha alma, pelo nosso amor to peço, pela nossa filha..."
    mv "Vamos seja para onde for, para a cabana de algum pobre pescador desses contornos, mas para ali não, oh!"
    mv "Não."
    mc "Em verdade nunca te vi assim."
    mc "Nunca pensei que tivesses a fraqueza de acreditar em agouros."
    mc "Não há senão um temor justo, Madalena, é o temor de Deus, 35 não há espectros que nos possam aparecer senão os das más ações que fazemos."
    mc "Que tens tu na consciência que tos faça temer?"
    mc "O teu coração e as tuas mãos estão puras, para os que andam diante de Deus, a Terra não tem sustos, nem o Inferno pavores que se lhes atrevam."
    mc "Rezaremos por alma de D. João de Portugal nessa devota capela que é parte da sua casa, e não hajas medo que nos venha perseguir neste mundo aquela santa 40 alma que está no Céu, e que em tão santa batalha, pelejando pelo seu Deus e por seu rei, acabou mártir às mãos dos infićis."
    mc "Vamos, D. Madalena de Vilhena, lembrai-vos de quem sois e de quem vindes, senhora..."
    mc "E não me tires, querida mulber, com vas quimeras de crianças, a tranquilidade do espírito e a força do coração, que as preciso inteiras nesta hora."
    mv "Pois que vais tu fazer?"
    mc "Vou, já te disse, vou dar uma lição aos nossos tiranos que lhes há de lembrar, vou dar um exemplo a este povo que os há de alumiar..."
    jump cena9

label cena9: # Manuel de Sousa, Madalena, Telmo, Miranda e outros criados entrando apressadamente
    tp "Senhor, desembarcaram agora grande comitiva de fidalgos, escudeiros e soldados que vêm de Lisboa e sobem a encosta para a vila."
    tp "O arcebispo não é decerto, 50 que já está há muito no convento, diz-se por aí..."
    mc "Que são os governadores?"
    "Telmo faz um sinal afirmativo"
    mc "Quiseram-me enganar, e apressam-se a vir hoje..."
    mc "Parece que adivinharam..."
    mc "Mas não me colheram desapercebido."
    "Manuel atira uma tocha para a porta da esquerda, pegando fogo á mesma"
    mc "Jorge, Maria!"
    "Manuel voltasse para Madalena"
    mc "Madalena, já, já sem mais demora."
    jump cena10

label cena10: # Manuel de Sousa, Madalena, Telmo, Miranda e outros criados, Maria, Jorge (entrando)
    mc "Jorge, acompanha estas damas."
    mc "Telmo, ide, ide com elas."
    "Manuel virasse para os outros criados"
    mc "Partiu já tudo, as arcas, os meus cavalos, armas e tudo o mais?"
    m "Quase tudo foi já, o pouco que falta está pronto e sairá num instante..."
    m "Pela porta de trás, se quereis."
    mc "Bom, que saia."
    "Miranda sinaliza a dois criados, e os mesmos saem"
    mc "Madalena, Maria... Não vos quero ver aqui mais."
    mc "Já, ide, serei convosco em pouco tempo."
    jump cena11

label cena11: # Manuel de Sousa, Miranda e os outros criados
    mc "Meu pai morreu desastrosamente caindo sobre a sua própria espada."
    mc "Quem sabe se eu morrerei nas chamas ateadas por minhas mãos?"
    mc "Seja."
    mc "Mas fique-se aprendendo em Portugal como um homem de honra e coração, por mais poderosa que seja a tirania, sempre lhe pode resistir, em perdendo o amor a coisas tão vis e precárias como são esses haveres que duas faíscas destroem num momento..."
    mc "Como é esta vida miserável que um sopro pode apagar em menos tempo ainda!"
    "Arrebata duas tochas das mãos dos criados, corre à porta da esquerda, atira com uma para dentro, e vê-se atear logo uma labareda imensa."
    "Vai ao fundo, atira a outra tocha, e sucede o mesmo."
    "Ouve-se alarido de fora."
    jump cena12

label cena12: # Manuel de Sousa e criados, Madalena, Maria, Telmo e Jorge (acudindo)
    mv "Que fazes?..."
    mv "Que fizeste?"
    mv "Que é isto, oh meu Deus!"
    "Manuel virasse para Madalena, e fala tranquilamente:"
    mc "Ilumino a minha casa para receber os muito pode-rosos e excelentes senhores governadores destes reinos."
    mc "Suas excelências podem vir, quando quiserem."
    mv "Meu Deus, meu Deus!..."
    mv "Ai, e o retrato de meu marido!..."
    mv "Salvem-me aquele retrato!"
    "Miranda e outros criados vão para tirar o painel, e uma coluna de fogo salta nas tapeçarias e os afugenta."
    mc "Parti, parti!"
    mc "As matérias inflamáveis que eu tinha disposto vão-se ateando com espantosa velocidade."
    mc "Fugi!"
    "Madalena, cingindo-se ao braço do marido:"
    mv "Sim, sim, fujamos."
    "Maria, tomando-o do outro braço"
    mn "Meu pai, nós não fugimos sem vós."
    t "Fujamos! Fujamos!..."
    "Redobram os gritos de fora, ouve-se rebate de sinos, cai o pano."