# The script of the game goes in this file.

# Declare characters used by this game. The color argument colorizes the
# name of the character.

define m = Character("Manuel")
define j = Character("Jorge")
define t = Character("Telmo")
define c = Character("Converso")
define r = Character("Romeiro")
define md = Character("Madalena")
define co = Character("Coro")
define p = Character("Prior")
define ma = Character("Maria")


label start:

    # Scene Prelogue
    scene bg Prelogue
    "Ato Terceiro"
    
    "Parte baixa do palácio do D. João de Portugal, comunicando, pela porta à esquerda do espectador, com a capela da Senhora da Piedade, na igreja de S. Paulo dos Dominicos de Almada: é um casarão vasto, sem ornato algum."
    "Arrumadas às paredes, em diversos pontos, escadas, tocheiras, cruzes, círias e outras alfaias e guisamentos de igreja de uso conhecido."
    "A um lado um esquife dos que usam as confrarias, do outro, uma grande cruz negra de tábua com o letreiro I.N.R.I. e toalha pendente, como se usa nas cerimónias da Semana Santa."
    "Mais para a cena uma velha com dous ou três tamboretes, a um lado, uma tocheira baixa com tocha acesa e já bastante gasta; sobre a mesa um castiçal de chumbo, de credência, baixo e com vela acesa também, e um hábito completo de religioso dominico, túnica, escapulário, rosário, cinto, etc. "
    "No fundo, porta que dá para as oficinas e aposentos que ocupam o resto dos baixos do palácio.- É alta noite."

    # Scene 1
    scene bg scene1
    "MANUEL DE SOUSA, sentado num tamborete ao pé da mesa, o rosto inclinado sobre o peito, os braços caídos e em completa prostração de espírito e corpo."
    "Num tamborete do outro lado, JORGE, meio encostado para a mesa, com as mãos postas, e os olhos pregados no irmão."
    m "Oh minha filha, minha filha! (silêncio longo) Desgraçada filha, que ficas órfã! (levanta o olhar de pai e de mãe... (pausa)...) e de família e de nome, que tudo perdeste hoje... (Levanta-se com violenta aflição.) A desgraça nunca os teve."
    m "Oh Jorge, que esta lembrança é que me mata, que me desespera! (apertando a mão do irmão, que se levantou após dele e o está consolando do gesto) É o castigo terrível do meu erro... se foi erro... crime sei que não foi. É sabe-o Deus, Jorge, e castigou-me assim, meu irmão!"
    j "Paciência, paciência: os seus juízos são imperscrutáveis. (Acalma e faz sentar o irmão: tornam a ficar ambos como estavam.)"
    m " Mas eu em que mereci ser feito o homem mais infeliz da Terra, posto de alvo à irrisão e ao discurso do vulgo?"
    m "Manuel de Sousa Coutinho, o filho de Lopo de Sousa Coutinho, o filho de nosso pai, Jorge!"
    j "Tu chamas-te o homem mais infeliz da Terra... Já te esqueceste que ainda está vivo aquele..."
    m "(caindo em si) – É verdade. (pausa; e depois, como quem se desdiz) Mas não é, nem tanto; padeceu mais, padeceu mais longamente, e bebeu até às fezes o cálice das amarguras humanas... (levantando a voz)"
    m "Mas fui eu, eu que lho preparei, eu que lho dei a beber, pelas mãos... inocentes8 mãos!... dessa infeliz que arrastei na minha queda, que lancei nesse abismo de vergonha, a quem cobri as faces as faces puras, e que não tinham corado doutro pejo  senão do da virtude e do recato..."
    m "cobri-lhas de um véu de infâmia que nem a morte há de levantar, porque lhe fica, perpétuo e para sempre, lançado sobre o túmulo a cobrir-lhe a memória de sombras... de manchas que se não lavam!"
    m "Fui eu o autor de tudo isto, o autor da minha desgraça e da sua desonra deles... Sei-o, conheço-o, e não sou mais infeliz que nenhum?"
    j "Vê a palavra que disseste: «desonra»: lembra-te dela e de ti, e considera se podes pleitear misérias com esse homem a quem Deus não quis acudir a morte antes de conhecer essa outra agonia maior. Ele não tem..."
    m "Ele não tem uma filha como eu, desgraçado... (pausa) – uma filha bela, pura, adorada, sobre cuja cabeça – oh, porque não é na minha!"
    m "vai cair toda essa desonra, toda a ignomínia  e todo o opróbrio que a injustiça do mundo, não sei porquê, me não quer lançar no rosto a mim, para pôr tudo na testa branca e pura de um anjo que não tem outra culpa senão a da origem que eu lhe dei."
    j "Não é assim, meu irmão, não te cegues com a dor, não te faças mais infeliz do que és. Já não és pouco, meu pobre Manuel, meu querido irmão! e Deus há de levar em conta essas amarguras."
    j "Já que te não pode apartar o cálice dos pejos, o que tu padecês há de ser descontado nela, há de resgatar a culpa."
    m "Resgate! sim, para o Céu; nesse confio eu... mas o mundo?"
    "..."
    j "Deixa o mundo e as suas vaidades."
    m "Estão deixadas todas. Mas este coração é de carne."
    j "Deus, Deus será o pai de tua filha."
    m "Olha, Jorge: queres que te diga o que eu sei decerto, e que devia ser consolação... mas não é, que eu sou homem, não sou anjo, meu irmão – devia ser consolação, e é desespero, e corrói de espinhos de toda esta paixão que estou passando..."
    m "é que a minha filha... Maria... a filha do meu amor –, a filha do meu pecado, se Deus quiser que seja pecado –, não vive, não resiste, não sobrevive a esta afronta."
    "Manuel desata a soluçar, cai com os cotovelos fixos na mesa e as mãos apertando o rosto; fica nesta posição por longo tempo. Ouve-se de quando em quando um soluço cumprido. Frei Jorge está em pé, detrás dele, amparando o seu corpo, e os olhos postos no Céu."
    j "(chamando timidamente) – Manuel!"
    m "Que me queres, irmão?"
    j "(animando-o) – Ela não está tão mal: já lá estive hoje..."
    m "Estiveste?... oh! conta-me, conta-me; eu não tenho... não tive ainda ânimo de a ir ver."
    j "Haverá duas horas que entrei na sua câmara, e estive ao pé do leito. Dormia, e mais sossegada da respiração."
    j "O acesso de febre que a tomou quando chegaram de Lisboa e que viu a mãe naquele estado, parecia declinar... quebrar-se mais alguma coisa."
    j "Doroteia e Telmo, pobre velho, coitado! ... estavam ao pé dela, cada um de seu lado... disseram-me que não tinha tornado a... a..."
    m "A lançar sangue?... Se ela deitou o do coração!... não tem mais. Naquele corpo tão franzino, tão delgado, que mais sangue há de haver? – Quando ontem a arranquei de ao pé da mãe e a levava nos braços, não mo lançou todo às golfadas aqui no peito?"
    m "(Mostra um lenço branco todo manchado de sangue.) Não o tenho aqui... o sangue... o sangue da minha vítima... que é o sangue das minhas veias... que é sangue da minha alma – é o sangue da minha querida filha! (Beija o lenço muitas vezes.)"
    m "Oh meu Deus, meu Deus! eu queria pedir-te que a levasses já... e não tenho ânimo. Eu devia aceitar por mercê de tuas misericórdias que chamasses aquele anjo para junto dos teus, antes que o mundo, este mundo infame e sem comiseraçã12o, ${16}$ lhe cuspisse na cara com a desgraça do seu nascimento."
    m "Devia, devia... e não posso, não quero, não sei, não tenho ânimo, não tenho coração. Peço-te vida, meu Deus, (ajoelha e põe as mãos) peço-te vida, vida, vida... vida para ela, vida para a minha filha!"
    "..."
    m "eu queria ver a filha do meu pecado!"
    m "E morra eu de vergonha, se é preciso"
    m "cubra-me de escárnio do mundo, desonre-me o opróbrio dos homens, tape-me a sepultura uma laje de ignomínia, um epíteto que me brade por essas eras desonra e infâmia sobre mim!"
    m "Oh meu Deus, meu Deus!"
    "Cai de bruços no chão... Passado algum tempo, Frei Jorge se chega para o levantar, e o quase o pega, e torna a assentar"
    j "Meu bom Manuel, Deus sabe melhor o que nos convém a todos:"
    j "põe nas suas mãos esse pobre coração, que não é resignado e contrito meu irmão, e Ele fará o que em sua misericórdia sabe que é melhor"
    m "(com voz metódica e medo) – Então desenganas-me... desenganas-me já?... é isso, que queres dizer? Fala, homem: não há que esperar! ... não há que esperar dali, não é assim?"
    j "Não disse tal."
    j "Por caridade comigo, meu irmão, não imagines tal. Eu disse-te a verdade:"
    j "Maria pareceu-me nisto opimida, dormia..."
    m "(variando) – Se Deus quiser que não acordasse! Jorge – Valha-te Deus!"
    m "Pois para mim qui está esta mortalha?"
    m "(tocando no hábito) morri hoje... vou amortalhar-me logo"
    m "e adeus tudo o que era mundo para mim!"
    m "Mas minha filha não era do mundo... não era, Jorge"
    m "tu bem sabes que não era: foi um anjo que veio do Céu para me acompanhar na peregrinação da Terra, e que me apontava sempre, a cada passo da vida, para a eterna pousada onde viera e onde me conduzia..."
    m "Separou-nos o arcanjo das desgraças, o ministro das iras do Senhor, que derramou sobre mim o vaso cheio das lágrimas, e a taça rasa das amarguras ardentes de sua cólera..."
    m "Vou com esta mortalha para a sepultura, e vivo, se morra, e deixo a minha filha no meio dos homens que a não conheceram, que a não hão de conhecer nunca, porque ela não era deste mundo, nem para ele..."
    m "Torna lá, Jorge, vai vê-la outra vez, vai e vem-me dizer; que eu ainda não posso... mas hei de ir, oh! hei de ir vê-la e beijá-la antes de descer à cova..."
    m "Tu não queres; não podes querer..."
    j "Havemos de ir, quando estiveres mais sossegado... havemos de ir ambos: descansa, hás de vê-la"
    j "Mas isto inda é cedo."
    m "Que horas serão?"
    j "Quatro, quatro e meia"
    "Vai á porta da esquerda e volta"
    j "São cinco horas, pelo alvor ${21}$ que já dá nos vidros da igreja."
    j "Daqui a pouco iremos"
    j "mas sossega"
    m  "É a outra... a outra desgraçada, meu irmão!"
    j "Essa – imagina por ti – está como não podia deixar de estar; mas a confiança em Deus pode muito: vai-se conformando"
    j "O Senhor fará o resto."
    j "Eu tenho fé neste escapulário (tocando no hábito em cima da mesa) para ti e para ela."
    j "Foi uma resolução digna de vós, foi uma inspiração divina que os iluminou a ambos."
    j "Deixa estar;"
    j "ainda pode haver dias felizes para quem soube consagrar a Deus as suas desgraças."
    m "E está tudo pronto?"
    m "Eu não sofro nestes hábitos, eu não aturo, com estes votos de vivo, a luz deste dia que vem a nascer."
    j "Está tudo concluído."
    j "O arcebispo mostrou-se bem e piedoso prelado ao contrário do pobre do velho que quase nada do que era preciso, e deu a minha filha o que ele não tinha, e agora vai ser preciso pedir ao vigário;"
    j "para que não faltasse o que é para o santo homem, e ao contrário do pobre do velho que quase nada fez."
    j "nada desde o romper do dia. Mandou-se ao provincial, e pela sua parte e pela nossa tudo está corrente."
    j "Frei João de Portugal, que é o Prior de Benfica, e também vigário do Sacramento, chegou haverá duas horas, noite fechada ainda, e cá está:"
    j "é quem me há de lançar o hábito, e é a Dona... a minha irmã."
    j "Depois iréis, segundo vosso desejo, um para Benfica, outro para o Sacramento."
    m "Tu és um bom irmão, Jorge."
    "Aperta-lhe a mão"
    m "Deus to há de pagar."
    m "Eu não me atrevo... tenho repugnância... mas é forçoso perguntar-te por alguém mais. Onde está ele... e o que fará?..."
    j "Bem sei, não digas mais: o romeiro."
    j "stá na minha cela, e de lá não há de sair – que foi ajustado entre nós – senão quando... quando eu lhe disser."
    j "Descansa: não verá ninguém, não será visto de ninguém daqueles que o não devem ver."
    j "Demais, o segredo é o que há de veríssimo entre mim e ti – além do arcebispo, a quem foi indispensável comunicar tudo para evitar todas as formalidades e delongas que aliás havia de haver numa separação desta ordem."
    j "Ainda há outra pessoa com quem lhe prometi – não pude deixar de prometer;"
    j "porque sem isso não queria de entrar em acordo algum – com quem lhe prometi que havia de falar hoje e antes de mais nada."
    m "Quem? será possível?"
    "..."
    m "Pois esse homem quer ter a crueldade de rasgar, fevra a fevra, os pedaços daquele coração já partido?"
    m "Não tem entranhas esse homem: sempre assim foi, duro, desapiedado como a sua espada."
    m "É D. Madalena que ele quer ver?..."
    j "Não, homem; é o seu aio velho, é Telmo Pais."
    j "Como lhe havia de eu recusar!"
    m "De nenhum modo: fizeste bem; eu é que sou injusto."
    m "Mas o que eu padeço é tanto e tal!..."
    m "Vamos; eu ainda me não entendo muito bem com esta desgraça; dize-me, fala-me a verdade: minha mulher... – minha mulher!"
    m "com que boca pronuncio eu ainda estas palavras!"
    m "D. Madalena o que sabe?"
    j "O que lhe disse o romeiro naquela fatal sala dos retratos...o que já te contei."
    j "Sabe que D. João está vivo, mas não sabe onde: supõe pôe-no na Palestina talvez;"
    j "é onde o deve supor pelas palavras que ouviu."
    m "Então não conhece como eu, toda a extensão, toda a indubitável verdade da nossa desgraça."
    m "Ainda bem; talvez possa ainda consolar-se com alguma esperança de..."
    j "Não. Ontem de tarde não;"
    j "mas esta noite começava a raiar-lhe no espírito alguma falsa luz de esperança."
    j "Deus há de deixá, se é para bem seu."
    m "Porque não há de deixar? Não há de deixar."
    j "Não sei. Ninguém lho disse, nem nas agonias da morte."
    j "Mas..."
    m "Também não; mas esta noite viu; há de adivinhar."
    m "Tenho medo que o faça..."
    j "Deus será connosco e com ela."
    j "E Maria, pobre filha, já lhe assegurei"
    j "acreditou me"
    j "que a mãe estava melhor, que tu ias logo vê-la, ao menos por ora..."
    m "Minha pobre filha, minha querida filha!"
    "Mas não: Telmo não lhe diz nada por certo; assim espero que, até lá por meio do que tu lhe disseste, possamos conservar em completa ignorância."
    "E Deus. Depois ir-se-lhe-á dizendo, pouco a pouco, até onde for inevitável."

    # Scene 2
    scene bg scene2
    m "É a voz de Jorge!"
    j "Entrai."
    t "Acordou."
    j "E como está?"
    t "Melhor, muito melhor, parece outra."
    t "Está muito abatida, isso sim, muito fraca;"
    t "a voz tem, mas os olhos serenos, animados como dantes e sem aquele fulgáz de ontem."
    m "Não pela mãe?"
    t "Nunca mais falou nela."
    m "Oh! Ah!"
    j "Temos de vê-la."
    m "Prontamente."
    t "(pega na mão do irmão) – Tu prometes-me.."
    j "Vamos (chamando a Telmo para a boca da cena)"
    j "Ouvi, Telmo: lembrai-vos do que vos disse esta manhã?"
    t "Não me hei de lembrar?"
    j "Ficais aqui."
    j "Em nós saindo, puxai aquela corda que vai dar à sineta da sacristia: virá um irmão converso;"
    j "dizei-lhe o vosso nome, ele ir-se-á sem mais palavra, e vós entrai."
    j "Fechai logo esta porta por dentro, e não abrais senão à minha voz. Entendestes?"
    t "Ide descansado."

    # Scene 3
    scene bg scene3
    "Telmo vai para deitar a mão à corda, para, suspenso, algum tempo, e depois"
    t "Vamos: isto há de ser."
    "Ouve-se tocar longe uma sineta: Telmo fica pensativo e com o braço levantado no ar."
    c "Quem sois?"
    t "Telmo Pais."
    "O converso faz vénia e vai-se."

    # Scene 4
    scene bg scene4
    t "Virou-se-me a alma toda com isto: não sou já o mesmo homem. Tinha um pressentimento do que havia de acontecer... parecia-me que não podia deixar de suceder... e cuidei que o desejava enquanto não veio."
    t "Veio, e fiquei mais aterrado, mais confuso que ninguém!"
    t "Meu honrado amo, o filho do meu nobre senhor está vivo... o filho que eu criei nestes braços... vou saber novas certas dele – no fim de vinte anos de o julgarem todos perdido – e eu, eu que sempre esperei, que sempre suspirei pela sua vinda..."
    t "era um milagre que eu esperava sem o crer!"
    t "eu agora tremo..."
    t "É que o amor desta outra filha, desta última filha, é maior, e venceu... venceu, apagou o outro."
    t "Perdoe-me, Deus, se é pecado. Mas que pecado há de haver com aquele anjo? Se ela me vir, se escapará desta sorte terrível!"
    t "Meu Deus, meu Deus! (Ajoelha) Levai o velho que já não presta para nada, levai-o por quem sois!"
    "Aparece o Romeiro à porta da esquerda, e vem lentamente aproximando-se de Telmo que não dá por ele."
    t "Contentai-vos com este pobre sacrifício de vida vã, Senhor, e não tomeis de nós o inocentinho que eu criei para vós, Senhor, para vós..."
    t "ainda não, não, não leveis ainda. Já padeceu muito, já traspassaram bastantes dores aquela alma; esperai-lhe com a da morte algum tempo!"

    # Scene 5
    scene bg scene5
    t "Quem sois vós?"
    r "Um pobre Romeiro."
    t "Que quereis?"
    r "Falar a Manuel de Sousa Coutinho."
    t "Não está."
    r "Esperarei."
    t "Não pode ser."
    r "Por que não?"
    t "Porque não pode ser."
    r "Dizei-lhe que está aqui um Romeiro."
    t "Não posso."
    r "Por que não?"
    t "Porque não posso."
    r "Pois então..."
    t "Ide-vos."
    r "Não me irei."
    t "Ide-vos, ide-vos, que não pode ser."
    r "Não me irei sem falar a Manuel de Sousa Coutinho."
    t "Não pode ser."
    r "Dizei-lhe que está aqui um Romeiro."
    t "Não posso."
    r "Pois então..."
    t "Ide-vos."
    r "Não me irei."
    t "Ide-vos, ide-vos, que não pode ser."
    r "Não me irei sem falar a Manuel de Sousa Coutinho."
    r "Que não ouça Deus o teu rogo!"
    t "Que voz!"
    t "Ah! é o Romeiro."
    t "Que me não ouça Deus! Porquê?"
    r "Não pedis tu pelo teu desgraçado amo, pelo filho que criaste?"
    t "Já não sei pedir senão pela outra."
    t "(Alto) E que pedisse por ele, ou por outrem, porque me não há de ouvir Deus, se lhe peço a vida de um inocente?"
    r "E quem te disse que ele o era?"
    t "Esta voz... esta voz!"
    t "Romeiro, quem és tu?"
    r "(tirando o chapéu e levantando o cabelo dos olhos) Ninguém, Telmo, ninguém, se nem já tu me conheces."
    t "(deitando-se-lhe às mãos para lhas beijar) – Meu amo, meu senhor... sois vós?"
    r "Eu fui João!"
    t "Meu filho!... oh! é o meu filho todo: a voz, o rosto... Só estas barbas, este não..."
    t "Mais branco já que o meu, senhor!"
    r "São vinte anos de cativeiro e miséria, de saudades, de ânsias que por aqui passaram."
    r "Para a cabeça bastou um mês como o que veio depois da batalha de Alcácer;"
    r "a barba, acabaram de a curar o sol da Palestina e as águas do Jordão."
    t "E por tão longe andaste!"
    r "E por tão longe te morrera!"
    r "Mas não quis Deus assim."
    t "Seja feita a Sua vontade."
    r "Pesa-te?"
    t "Oh, senhor!"
    r "Pesa-te?"
    t "Há de me pesar da vossa vida? (à parte) Meu Deus, parece-me que menti..."
    r "E porque não, se já me pesa a mim dela, se tanto me pesa ela a mim?"
    r "Amigo, ouve..."
    t "Não sou?"
    r "És: bem sei."
    r "E contudo, vinte anos de ausência, e de conversação de novos amigos, fazem esquecer tanto os velhos!..."
    r "Mas tu és meu amigo. E se tu o não foras, quem o seria?"
    t "Senhor!"
    r "Eu não quis acabar com isto, não quis pôr em efeito a minha última resolução sem falar contigo, sem ouvir da tua boca..."
    t "Que quereis que vos diga, senhor?"
    t "Eu..."
    r "Tu, bem sei que duvidaste sempre da minha morte, que não quiseste ceder a nenhuma evidência: não me admirou de ti, meu Telmo."
    r "Mas também não posso"
    r "Deus me ouve, não posso crimimar ninguém porque o acreditasse: as provas eram de convencer todo..."
    r "…desonra e vergonha! Na hora em que ela acreditou na minha morte, nessa hora morri. Com a mão que deu a outro riscou-me do número dos vivos."
    r "D. João de Portugal não há de desonrar a sua viúva."
    r "Não: vai, dito por ti terá dobrada força: dize-lhe que falaste com o romeiro, que o examinaste, que o convenceste de falso e de impostor... dize o que quiseres, mas salva-a da vergonha, e ao meu nome da afronta."
    r "De mim já não há senão esse nome, ainda honrado: a ela memória dele que fique sem mancha."
    r "Está em tuas mãos, Telmo, entrego-te mais que a minha vida."
    r "Queres faltar-me agora?"
    t "Não, meu senhor: a resolução é nobre e digna de vós."
    t "Mas pode ela aproveitar ainda?"
    r "Porque não?"
    t "Eu sei!"
    t "Talvez..."

    # Scene 6
    scene bg scene6
    md "Esposo, esposo!"
    md "abri-me, por quem sois!"
    md "Bem sei que aqui estais: abri!"
    r "É ela que me chama."
    r "Santo Deus! Madalena que chama por mim..."
    t "Por vós!"
    r "Pois por quem?"
    r "não lhe ouves gritar: – «esposo, esposo?»"
    md "Marido da minha alma, pelo nosso amor te peço, pelos doces nomes que me deste, pelas memórias da nossa felicidade antiga,"
    md "pelas saudades de tanto amor e tanta ventura, oh! não me negues este último favor!"
    r "Que encanto, que sedução!"
    r "Como lhe hei de resistir!"
    md "Meu marido, meu amor, meu Manuel!"
    r "Ah!... E eu tão cego que já tomava para mim!..."
    r "Céu e inferno! abra-se esta porta..."
    r "Não: o que é dito, é dito."
    "Romeiro vai precipitadamente à corda da sineta, toca com violência; aparece o mesmo irmão converso, e a um sinal do Romeiro ambos desaparecem pela porta da esquerda."

    # Scene 7
    scene bg scene7
    "Madalena (ainda de fora.)"
    md "Jorge, meu irmão, Frei Jorge, vós estais aí, que eu bem sei; abri-me por caridade, deixai-me dizer uma única palavra a meu... a vosso irmão: – não vos importuno mais, e farei tudo o que de mim quereis, e..."
    "(Ouve-se do mesmo lado ruído de passos apressados, e logo a voz de Frei Jorge.)"
    j "Telmo, Telmo, abri, se podeis... abri já."
    "Telmo abre a porta."
    t "Aqui estou eu."
    "Madalena entra desgrenhada e fora de si, procurando com os olhos todos os recantos da casa."
    md "Estais aqui só, Telmo! E ele para onde foi?"
    t "Ele quem, senhora?"
    "Jorge vem à frente."
    j "Telmo estava aqui aguardando por mim, e com ordem de não abrir enquanto eu não visse."
    md "Aqui havia duas vozes que falavam: distintamente as ouvi."
    "Telmo, aterrorizado."
    t "Ouviste?"
    md "Sim, ouvi. Onde está ele, Telmo: onde está meu marido... Manuel de Sousa?"
    "Manuel, que tem estado no fundo enquanto Madalena, sem o ver, se adiantara para a cena, vem agora à frente."
    m "Esse homem está aqui, senhora; que lhe quereis?"
    md "Oh, que tom, que modo esse com que me falas!..."
    "Manuel entrefece-se, depois cai em si, gravemente."
    m "Madalena... Senhora, como quereis que vos fale, que quereis que vos diga? – Não está tudo dito entre nós?"
    md "Tudo! quem sabe? Eu parece-me que não. Olha: eu sei... mas não daríamos nós, com demasiada precipitação, uma fé tão cega, uma crença tão implícita a essas misteriosas palavras de um romeiro, um vagabundo... um homem enfim que ninguém conhece? Pois dize..."
    "Telmo, à parte, a Jorge."
    t "Tenho que vos dizer, ouvi."
    "Telmo e Jorge conversam ambos à parte em voz baixa."
    m "Oh Madalena, Madalena! não tenho mais nada que te dizer. Crê-me, que to juro na presença de Deus: a nossa união, o nosso amor é impossível."
    "Jorge continua a conversação com Telmo, e levanta a voz com aspereza."
    j "É impossível, já agora... – e sempre o devia ser."
    "Madalena vira-se para Jorge."
    md "Também tu, Jorge!"
    "Jorge volta-se para ela."
    j "Eu falava com Telmo, minha irmã."
    j "Ide, Telmo, eu vos disse, que sois mais preciso lá."
    "Fala-lhe ao ouvido; depois, alto."
    j "Não ma deixes um instante, ao menos até passar a hora fatal."
    "Telmo sai com repugnância, e rodeando para ver se chega ao pé de Madalena. Jorge, que o percebe, faz-lhe um sinal imperioso; ele recua, e finalmente se retira pelo fundo."

    # Scene 8
    scene bg scene8
    md "Jorge, meu irmão, meu bom Jorge, vós, que sois tão prudente e reflectido, não dais nenhuma esperança à mínima dúvida?"
    j "Tomara eu ser tão feliz que pudesse, querida irmã..."
    md "Pois entendês?..."
    m "Madalena... senhora! Todas estas cousas são já inúteis de nós... Até ontem, a nossa desculpa, para com Deus e para com os homens, estava na boa-fé e segurança de nossas consciências. Essa acabou."
    m "Para nós já não há senão estes mortais conselhos, o dos hábitos de cima da banca, e a sepultura de um túmulo."
    m "A resolução que tomamos é a única possível; e já não há que voltar atrás... Ainda ontem falávamos dos conselhos de um Vimoso... que nos diria... oh, incompreensíveis mistérios de Deus!"
    m "Ânimo, e ponhamos os olhos naquela cruz!"
    m "Pela última vez, Madalena, pela derradeira vez neste mundo, querida..."
    "(Vai para a abraçar e recua.)"
    m "Adeus, adeus!"
    "(Foge precipitadamente pela porta da esquerda.)"

    # Scene 9
    scene bg scene9
    md "Ouve, espera: uma só, uma só palavra, Manuel de Sousa!..."
    "(Toca o órgão dentro.)"
    "Coro (dentro): De profundis clamavi ad te, Domine; Domine, exaudi vocem meam."
    md "Oh Deus, Senhor meu! pois já, já não mais um instante, meu Deus?"
    md "Cruz do meu Redentor, oh cruz preciosa, refúgio de infelizes, ampara-me tu, que me abandonaram todos neste mundo, e já não posso com as minhas desgraças..."
    md "...e estou feita um espetáculo de dor e espanto para o Céu e para a Terra!"
    md "Tomai, Senhor, tomai tudo..."
    md "A minha filha também?... oh! a minha filha, a minha filha... também essa vos dou, meu Deus!"
    md "E agora, que mais quereis de mim, Senhor?"
    "(Toca o órgão outra vez.)"
    "Coro (dentro): Fiant aures tuae intendentes, in vocem deprecationis meae."
    j "Vinde, minha irmã, é a voz do Senhor que vos chama. Vai começar a santa cerimónia."
    md "Ele foi?"
    j "Foi sim, minha irmã."
    md "E eu vou."
    "(Saem ambos pela porta do fundo.)"

    # Scene 10
    scene bg scene10
    "Manuel de Sousa está de joelhos, com o hábito de noviço vestido, à direita do Prior. O Arcebispo, de capa magna e barrete, está no seu trono, rodeado dos seus clérigos em sobrepelizes."
    "Pouco depois entra Jorge acompanhado de Madalena, também já vestida de noviça, que vai ajoelhar à esquerda do Prior. Toca o órgão."
    "Coro: Si iniquitates observaveris, Domine; Domine, quis sustinebit?"
    "O Prior toma os escapulários de cima do altar."
    j "Manuel de Sousa Coutinho, irmão Luís de Sousa, pois em tu me fizeste desprezar o homem velho, ambos que já fostes nobres senhores do mundo, e aqui estais prostrados no pó da terra, nesse humilde hábito de pobres noviços; que deixastes tudo, até vos deixar a vós mesmos..."
    j "Filhos de Jesus Cristo, e agora do nosso padre S. Domingos, recebei com este bentito escapulário..."

    # Scene 11
    scene bg scene11
    "Maria entra precipitadamente pela igreja em estado de completa alienação; traz umas roupas brancas, desalinhas e caídas, os cabelos soltos, o rosto macerado mas inflamado com as rosetas hécticas, os olhos desvairados."
    "Para um momento, reconhece os pais, e vai direita a eles. Espanto geral; a cerimônia interrompe-se."
    md "Ouve, espera: uma só, uma só palavra, Manuel de Sousa!..."
    "(Toca o órgão dentro.)"
    "Coro: De profundis clamavi ad te, Domine; Domine, exaudi vocem meam."
    md "Oh Deus, Senhor meu! pois já, já não mais um instante, meu Deus?"
    md "Cruz do meu Redentor, oh cruz preciosa, refúgio de infelizes, ampara-me tu, que me abandonaram todos neste mundo, e já não posso com as minhas desgraças..."
    md "...e estou feita um espetáculo de dor e espanto para o Céu e para a Terra!"
    md "Tomai, Senhor, tomai tudo..."
    md "A minha filha também?... oh! a minha filha, a minha filha... também essa vos dou, meu Deus!"
    md "E agora, que mais quereis de mim, Senhor?"
    "(Toca o órgão outra vez.)"
    "Coro: Fiant aures tuae intendentes, in vocem deprecationis meae."
    j "Vinde, minha irmã, é a voz do Senhor que vos chama. Vai começar a santa cerimónia."
    md "Ele foi?"
    j "Foi sim, minha irmã."
    md "E eu vou."
    "(Saem ambos pela porta do fundo.)"
    ma "Meu pai, meu pai, minha mãe, levantai-vos, vinde."
    "(Maria toma-os pelas mãos; eles obedecem maquinalmente, vêm ao meio da cena: confusão geral.)"
    md "Maria! Minha filha!"
    m "Filha, filha!... Oh, minha filha!..."
    "(Abraçam-se ambos nela.)"
    ma "Esperai: que não morre ninguém sem mim. Que quereis fazer? Que cerimônias são estas?"
    ma "Que é isso de assentar e esse altar, e querer roubar o pai e a mãe à sua filha?"
    ma "(para os circunstantes) Vós quem sois, espectros fatais?... quereis-nos tirar dos meus braços?"
    ma "Esta é a minha mãe, este é o meu pai... Que me importa a mim com o outro?"
    ma "Que ressuscite ou não, que fique com os mortos ou com os vivos – que se fique na cova ou que ressuscite agora!"
    ma "Mate-me, mate-me, se quereis, mas deixai-me este pai, esta mãe, que são meus."
    ma "Não me tireis agora no meio de uma família a dizer: «Vós não sois marido e mulher; vós não sois parentes; esta filha criada ao colo de tantas meiguices, de tanta ternura, esta filha não é vossa.»"
    ma "Mãe, mãe, eu o sabia... nunca to disse, mas sabia-o: tinha-mo dito aquele anjo que me apareceu todas as noites para me dizer que tu ias morrer."
    ma "(ajoelha-se junto à mãe) Mãe, mãe, eu não hei-de morrer sem ti."
    ma "(vai para o pai) Pai, este que aqui é meu pai, não quero antes que ele venha..."
    ma "(encolhendo-se no hábito do pai) Que me esconda aqui, antes que venha esse homem do outro mundo dizer-me na minha cara: tu eras um estranho, que esta filha é de velha e não é tua."
    ma "(vai para Madalena) Pobre mãe! tu não podes... coitada!... não tens ânimo... nunca mentiste?... Pois mente agora para salvar a honra de tua filha, para que lhe não tirem o nome de seu pai."
    md "Misericórdia, meu Deus!"
    ma "Não queres? Tu também não, pai? – Não querem. E eu hei de morrer assim... e ele vem aí..."

    # Scene 12
    scene bg scene12
    r "(para Telmo) Vai, vai; vê se ainda é tempo: salva-os, salva-os, que ainda podes..."
    "(Telmo dá alguns passos para diante.)"
    ma "(apontando para o Romeiro) É aquela voz, é ele, é ele! – Já não é tempo."
    ma "Minha mãe, meu pai, cobri-me bem estas faces, que morro de vergonha..."
    "(Maria esconde o rosto no seio da mãe.)"
    ma "Morro, morro... de vergonha..."
    "(Maria cai e fica morta no chão. Manuel de Sousa e Madalena prostram-se ao pé do cadáver da filha.)"
    m "(depois de algum espaço, levanta-se de joelhos) Minha irmã, rezemos por ela... encomendemos ao nosso anjo, que Deus levou para si."
    j "Padre Prior, podeis-lhe lançar aqui o escapulário?"
    j "(indo buscar os escapulários ao altar-mor e tornando) Meus irmãos, Deus aflige aqueles que ama. A coroa de glória não se dá senão no Céu."

    return
